
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(QtCore.QObject):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1032, 736)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.credits = QtWidgets.QPushButton(Dialog)
        self.credits.setObjectName("credits")
        self.horizontalLayout_32.addWidget(self.credits)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_32.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.patreonBtn = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/patreon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.patreonBtn.setIcon(icon)
        self.patreonBtn.setIconSize(QtCore.QSize(32, 32))
        self.patreonBtn.setObjectName("patreonBtn")
        self.horizontalLayout_5.addWidget(self.patreonBtn)
        self.discBtn = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/disc.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.discBtn.setIcon(icon1)
        self.discBtn.setIconSize(QtCore.QSize(32, 32))
        self.discBtn.setObjectName("discBtn")
        self.horizontalLayout_5.addWidget(self.discBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.radioInputVideos = QtWidgets.QRadioButton(Dialog)
        self.radioInputVideos.setChecked(True)
        self.radioInputVideos.setObjectName("radioInputVideos")
        self.horizontalLayout_15.addWidget(self.radioInputVideos)
        self.radioInputPNG = QtWidgets.QRadioButton(Dialog)
        self.radioInputPNG.setEnabled(True)
        self.radioInputPNG.setObjectName("radioInputPNG")
        self.horizontalLayout_15.addWidget(self.radioInputPNG)
        self.radioResumeRender = QtWidgets.QRadioButton(Dialog)
        self.radioResumeRender.setEnabled(True)
        self.radioResumeRender.setObjectName("radioResumeRender")
        self.horizontalLayout_15.addWidget(self.radioResumeRender)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self._2 = QtWidgets.QHBoxLayout()
        self._2.setObjectName("_2")
        self.inputVideosLayout = QtWidgets.QFrame(Dialog)
        self.inputVideosLayout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputVideosLayout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputVideosLayout.setObjectName("inputVideosLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.inputVideosLayout)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputFileBtn = QtWidgets.QPushButton(self.inputVideosLayout)
        self.inputFileBtn.setObjectName("inputFileBtn")
        self.horizontalLayout_2.addWidget(self.inputFileBtn)
        self.inputFileLabel = QtWidgets.QLabel(self.inputVideosLayout)
        self.inputFileLabel.setScaledContents(False)
        self.inputFileLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inputFileLabel.setObjectName("inputFileLabel")
        self.horizontalLayout_2.addWidget(self.inputFileLabel)
        self._2.addWidget(self.inputVideosLayout)
        self.inputSequenceLayout_2 = QtWidgets.QFrame(Dialog)
        self.inputSequenceLayout_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputSequenceLayout_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputSequenceLayout_2.setObjectName("inputSequenceLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.inputSequenceLayout_2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.inputFolderBtn = QtWidgets.QPushButton(self.inputSequenceLayout_2)
        self.inputFolderBtn.setObjectName("inputFolderBtn")
        self.horizontalLayout_13.addWidget(self.inputFolderBtn)
        self.inputFolderLabel = QtWidgets.QLabel(self.inputSequenceLayout_2)
        self.inputFolderLabel.setObjectName("inputFolderLabel")
        self.horizontalLayout_13.addWidget(self.inputFolderLabel)
        self._2.addWidget(self.inputSequenceLayout_2)
        self.inputResumeLayout_2 = QtWidgets.QFrame(Dialog)
        self.inputResumeLayout_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inputResumeLayout_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputResumeLayout_2.setObjectName("inputResumeLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.inputResumeLayout_2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.inputResumeFolder = QtWidgets.QPushButton(self.inputResumeLayout_2)
        self.inputResumeFolder.setObjectName("inputResumeFolder")
        self.horizontalLayout_16.addWidget(self.inputResumeFolder)
        self.inputResumeLabel = QtWidgets.QLabel(self.inputResumeLayout_2)
        self.inputResumeLabel.setObjectName("inputResumeLabel")
        self.horizontalLayout_16.addWidget(self.inputResumeLabel)
        self._2.addWidget(self.inputResumeLayout_2)
        self.verticalLayout.addLayout(self._2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.exportType = QtWidgets.QComboBox(Dialog)
        self.exportType.setEnabled(True)
        self.exportType.setObjectName("exportType")
        self.exportType.addItem("")
        self.exportType.addItem("")
        self.exportType.addItem("")
        self.exportType.addItem("")
        self.horizontalLayout_6.addWidget(self.exportType)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.outputFolderBtn = QtWidgets.QPushButton(Dialog)
        self.outputFolderBtn.setObjectName("outputFolderBtn")
        self.horizontalLayout_3.addWidget(self.outputFolderBtn)
        self.outputFolderLabel = QtWidgets.QLabel(Dialog)
        self.outputFolderLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.outputFolderLabel.setObjectName("outputFolderLabel")
        self.horizontalLayout_3.addWidget(self.outputFolderLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_31.addWidget(self.label_27)
        self.flowModel = QtWidgets.QComboBox(self.tab)
        self.flowModel.setObjectName("flowModel")
        self.flowModel.addItem("")
        self.horizontalLayout_31.addWidget(self.flowModel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.interpolMethod = QtWidgets.QComboBox(self.tab)
        self.interpolMethod.setModelColumn(0)
        self.interpolMethod.setObjectName("interpolMethod")
        self.interpolMethod.addItem("")
        self.interpolMethod.addItem("")
        self.interpolMethod.addItem("")
        self.interpolMethod.addItem("")
        self.horizontalLayout_9.addWidget(self.interpolMethod)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.modeDesc = QtWidgets.QLabel(self.tab)
        self.modeDesc.setObjectName("modeDesc")
        self.verticalLayout_7.addWidget(self.modeDesc)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.useHalf = QtWidgets.QCheckBox(self.tab_2)
        self.useHalf.setEnabled(True)
        self.useHalf.setChecked(True)
        self.useHalf.setObjectName("useHalf")
        self.verticalLayout_6.addWidget(self.useHalf)
        self.doBenchmark = QtWidgets.QCheckBox(self.tab_2)
        self.doBenchmark.setChecked(True)
        self.doBenchmark.setObjectName("doBenchmark")
        self.verticalLayout_6.addWidget(self.doBenchmark)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_30.addWidget(self.label_32)
        self.batchSize = QtWidgets.QSpinBox(self.tab_2)
        self.batchSize.setMinimum(1)
        self.batchSize.setObjectName("batchSize")
        self.horizontalLayout_30.addWidget(self.batchSize)
        self.verticalLayout_6.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_18.addWidget(self.label_16)
        self.deviceList = QtWidgets.QComboBox(self.tab_2)
        self.deviceList.setObjectName("deviceList")
        self.horizontalLayout_18.addWidget(self.deviceList)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.animMethod = QtWidgets.QComboBox(self.tab_2)
        self.animMethod.setObjectName("animMethod")
        self.animMethod.addItem("")
        self.animMethod.addItem("")
        self.verticalLayout_2.addWidget(self.animMethod)
        self.horizontalLayout_17.addLayout(self.verticalLayout_2)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.intAlgo = QtWidgets.QComboBox(self.tab_2)
        self.intAlgo.setObjectName("intAlgo")
        self.intAlgo.addItem("")
        self.intAlgo.addItem("")
        self.verticalLayout_4.addWidget(self.intAlgo)
        self.horizontalLayout_20.addLayout(self.verticalLayout_4)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_20)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fpsInput = QtWidgets.QLineEdit(self.tab_2)
        self.fpsInput.setObjectName("fpsInput")
        self.horizontalLayout.addWidget(self.fpsInput)
        self.interpolationLevel = QtWidgets.QComboBox(self.tab_2)
        self.interpolationLevel.setMinimumSize(QtCore.QSize(100, 0))
        self.interpolationLevel.setModelColumn(0)
        self.interpolationLevel.setObjectName("interpolationLevel")
        self.interpolationLevel.addItem("")
        self.interpolationLevel.addItem("")
        self.interpolationLevel.addItem("")
        self.horizontalLayout.addWidget(self.interpolationLevel)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.outputFps = QtWidgets.QLineEdit(self.tab_2)
        self.outputFps.setReadOnly(True)
        self.outputFps.setObjectName("outputFps")
        self.horizontalLayout.addWidget(self.outputFps)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_6.addWidget(self.line_6)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_26.addWidget(self.label_23)
        self.pngCompress = QtWidgets.QLineEdit(self.tab_2)
        self.pngCompress.setObjectName("pngCompress")
        self.horizontalLayout_26.addWidget(self.pngCompress)
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_26.addWidget(self.label_24)
        self.verticalLayout_6.addLayout(self.horizontalLayout_26)
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_6.addWidget(self.label_26)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_22 = QtWidgets.QLabel(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_25.addWidget(self.label_22)
        self.crfVal = QtWidgets.QLineEdit(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crfVal.sizePolicy().hasHeightForWidth())
        self.crfVal.setSizePolicy(sizePolicy)
        self.crfVal.setObjectName("crfVal")
        self.horizontalLayout_25.addWidget(self.crfVal)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_25)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.dontInterpolateScenes = QtWidgets.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.dontInterpolateScenes.setFont(font)
        self.dontInterpolateScenes.setObjectName("dontInterpolateScenes")
        self.horizontalLayout_14.addWidget(self.dontInterpolateScenes)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_14.addWidget(self.lineEdit_2)
        self.verifyScenes = QtWidgets.QPushButton(self.tab_3)
        self.verifyScenes.setObjectName("verifyScenes")
        self.horizontalLayout_14.addWidget(self.verifyScenes)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.line_5 = QtWidgets.QFrame(self.tab_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_8.addWidget(self.line_5)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.cleanInterpol = QtWidgets.QCheckBox(self.tab_3)
        self.cleanInterpol.setObjectName("cleanInterpol")
        self.horizontalLayout_19.addWidget(self.cleanInterpol)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.perfectLoop = QtWidgets.QCheckBox(self.tab_3)
        self.perfectLoop.setObjectName("perfectLoop")
        self.horizontalLayout_21.addWidget(self.perfectLoop)
        self.audioVersion = QtWidgets.QCheckBox(self.tab_3)
        self.audioVersion.setObjectName("audioVersion")
        self.horizontalLayout_21.addWidget(self.audioVersion)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.line_4 = QtWidgets.QFrame(self.tab_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_8.addWidget(self.line_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.fpsLimit = QtWidgets.QLineEdit(self.tab_3)
        self.fpsLimit.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.fpsLimit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fpsLimit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fpsLimit.setObjectName("fpsLimit")
        self.horizontalLayout_12.addWidget(self.fpsLimit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.to60 = QtWidgets.QCheckBox(self.tab_3)
        self.to60.setObjectName("to60")
        self.horizontalLayout_10.addWidget(self.to60)
        self.to60C1 = QtWidgets.QCheckBox(self.tab_3)
        self.to60C1.setObjectName("to60C1")
        self.horizontalLayout_10.addWidget(self.to60C1)
        self.to60C2 = QtWidgets.QCheckBox(self.tab_3)
        self.to60C2.setObjectName("to60C2")
        self.horizontalLayout_10.addWidget(self.to60C2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_3, "")
        self.PixelArt = QtWidgets.QWidget()
        self.PixelArt.setObjectName("PixelArt")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.PixelArt)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Alpha = QtWidgets.QLabel(self.PixelArt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Alpha.sizePolicy().hasHeightForWidth())
        self.Alpha.setSizePolicy(sizePolicy)
        self.Alpha.setObjectName("Alpha")
        self.verticalLayout_5.addWidget(self.Alpha)
        self.alphaOpt = QtWidgets.QComboBox(self.PixelArt)
        self.alphaOpt.setObjectName("alphaOpt")
        self.alphaOpt.addItem("")
        self.alphaOpt.addItem("")
        self.verticalLayout_5.addWidget(self.alphaOpt)
        self.verticalLayout_14.addLayout(self.verticalLayout_5)
        self.limitPalette = QtWidgets.QCheckBox(self.PixelArt)
        self.limitPalette.setObjectName("limitPalette")
        self.verticalLayout_14.addWidget(self.limitPalette)
        self.checkBox = QtWidgets.QCheckBox(self.PixelArt)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_14.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.PixelArt)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_14.addWidget(self.checkBox_2)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.pixelUpscaleDowscaleBefore = QtWidgets.QComboBox(self.PixelArt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixelUpscaleDowscaleBefore.sizePolicy().hasHeightForWidth())
        self.pixelUpscaleDowscaleBefore.setSizePolicy(sizePolicy)
        self.pixelUpscaleDowscaleBefore.setObjectName("pixelUpscaleDowscaleBefore")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.pixelUpscaleDowscaleBefore.addItem("")
        self.horizontalLayout_22.addWidget(self.pixelUpscaleDowscaleBefore)
        self.label_19 = QtWidgets.QLabel(self.PixelArt)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_22.addWidget(self.label_19)
        self.verticalLayout_14.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pixelDownscaleUpscaleAfter = QtWidgets.QComboBox(self.PixelArt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixelDownscaleUpscaleAfter.sizePolicy().hasHeightForWidth())
        self.pixelDownscaleUpscaleAfter.setSizePolicy(sizePolicy)
        self.pixelDownscaleUpscaleAfter.setObjectName("pixelDownscaleUpscaleAfter")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.pixelDownscaleUpscaleAfter.addItem("")
        self.horizontalLayout_23.addWidget(self.pixelDownscaleUpscaleAfter)
        self.label_20 = QtWidgets.QLabel(self.PixelArt)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_23.addWidget(self.label_20)
        self.verticalLayout_14.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pixelUpscaleAfter = QtWidgets.QComboBox(self.PixelArt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixelUpscaleAfter.sizePolicy().hasHeightForWidth())
        self.pixelUpscaleAfter.setSizePolicy(sizePolicy)
        self.pixelUpscaleAfter.setObjectName("pixelUpscaleAfter")
        self.pixelUpscaleAfter.addItem("")
        self.pixelUpscaleAfter.addItem("")
        self.pixelUpscaleAfter.addItem("")
        self.pixelUpscaleAfter.addItem("")
        self.pixelUpscaleAfter.addItem("")
        self.pixelUpscaleAfter.addItem("")
        self.pixelUpscaleAfter.addItem("")
        self.pixelUpscaleAfter.addItem("")
        self.pixelUpscaleAfter.addItem("")
        self.pixelUpscaleAfter.addItem("")
        self.horizontalLayout_24.addWidget(self.pixelUpscaleAfter)
        self.label_21 = QtWidgets.QLabel(self.PixelArt)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_24.addWidget(self.label_21)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.tabWidget.addTab(self.PixelArt, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.useResize = QtWidgets.QCheckBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.useResize.setFont(font)
        self.useResize.setToolTip("")
        self.useResize.setToolTipDuration(-1)
        self.useResize.setStatusTip("")
        self.useResize.setInputMethodHints(QtCore.Qt.ImhNone)
        self.useResize.setObjectName("useResize")
        self.horizontalLayout_4.addWidget(self.useResize)
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.widthValue = QtWidgets.QLineEdit(self.tab_4)
        self.widthValue.setInputMask("")
        self.widthValue.setText("")
        self.widthValue.setObjectName("widthValue")
        self.horizontalLayout_4.addWidget(self.widthValue)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.useSplit = QtWidgets.QCheckBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.useSplit.setFont(font)
        self.useSplit.setObjectName("useSplit")
        self.horizontalLayout_7.addWidget(self.useSplit)
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.splitSizeX = QtWidgets.QLineEdit(self.tab_4)
        self.splitSizeX.setToolTip("")
        self.splitSizeX.setWhatsThis("")
        self.splitSizeX.setAutoFillBackground(False)
        self.splitSizeX.setInputMask("")
        self.splitSizeX.setObjectName("splitSizeX")
        self.horizontalLayout_7.addWidget(self.splitSizeX)
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_7.addWidget(self.label_25)
        self.splitSizeY = QtWidgets.QLineEdit(self.tab_4)
        self.splitSizeY.setObjectName("splitSizeY")
        self.horizontalLayout_7.addWidget(self.splitSizeY)
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.splitPad = QtWidgets.QLineEdit(self.tab_4)
        self.splitPad.setObjectName("splitPad")
        self.horizontalLayout_7.addWidget(self.splitPad)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.brightBtn = QtWidgets.QPushButton(self.tab_6)
        self.brightBtn.setObjectName("brightBtn")
        self.horizontalLayout_8.addWidget(self.brightBtn)
        self.darkBtn = QtWidgets.QPushButton(self.tab_6)
        self.darkBtn.setObjectName("darkBtn")
        self.horizontalLayout_8.addWidget(self.darkBtn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.placeholderList = QtWidgets.QComboBox(self.tab_6)
        self.placeholderList.setObjectName("placeholderList")
        self.verticalLayout_17.addWidget(self.placeholderList)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.loadPlace = QtWidgets.QPushButton(self.tab_6)
        self.loadPlace.setObjectName("loadPlace")
        self.horizontalLayout_29.addWidget(self.loadPlace)
        self.deletePlace = QtWidgets.QPushButton(self.tab_6)
        self.deletePlace.setObjectName("deletePlace")
        self.horizontalLayout_29.addWidget(self.deletePlace)
        self.verticalLayout_17.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28.addLayout(self.verticalLayout_17)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem6)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.placeholderName = QtWidgets.QLineEdit(self.tab_6)
        self.placeholderName.setText("")
        self.placeholderName.setObjectName("placeholderName")
        self.verticalLayout_16.addWidget(self.placeholderName)
        self.savePlace = QtWidgets.QPushButton(self.tab_6)
        self.savePlace.setObjectName("savePlace")
        self.verticalLayout_16.addWidget(self.savePlace)
        self.horizontalLayout_28.addLayout(self.verticalLayout_16)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.textEdit = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit.setEnabled(True)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_9.addWidget(self.textEdit)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.fastMode = QtWidgets.QCheckBox(self.tab_7)
        self.fastMode.setObjectName("fastMode")
        self.verticalLayout_13.addWidget(self.fastMode)
        self.dontCleanCache = QtWidgets.QCheckBox(self.tab_7)
        self.dontCleanCache.setObjectName("dontCleanCache")
        self.verticalLayout_13.addWidget(self.dontCleanCache)
        self.ffmpegPrint = QtWidgets.QCheckBox(self.tab_7)
        self.ffmpegPrint.setObjectName("ffmpegPrint")
        self.verticalLayout_13.addWidget(self.ffmpegPrint)
        self.onlyInterpolateMissing = QtWidgets.QCheckBox(self.tab_7)
        self.onlyInterpolateMissing.setObjectName("onlyInterpolateMissing")
        self.verticalLayout_13.addWidget(self.onlyInterpolateMissing)
        self.debugKeepDuplicates = QtWidgets.QCheckBox(self.tab_7)
        self.debugKeepDuplicates.setObjectName("debugKeepDuplicates")
        self.verticalLayout_13.addWidget(self.debugKeepDuplicates)
        self.line_8 = QtWidgets.QFrame(self.tab_7)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_13.addWidget(self.line_8)
        self.line_7 = QtWidgets.QFrame(self.tab_7)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_13.addWidget(self.line_7)
        self.label_31 = QtWidgets.QLabel(self.tab_7)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_13.addWidget(self.label_31)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_30 = QtWidgets.QLabel(self.tab_7)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_27.addWidget(self.label_30)
        self.smoothFlow = QtWidgets.QSpinBox(self.tab_7)
        self.smoothFlow.setObjectName("smoothFlow")
        self.horizontalLayout_27.addWidget(self.smoothFlow)
        self.label_29 = QtWidgets.QLabel(self.tab_7)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_27.addWidget(self.label_29)
        self.flowForce = QtWidgets.QSpinBox(self.tab_7)
        self.flowForce.setMinimum(0)
        self.flowForce.setMaximum(40)
        self.flowForce.setProperty("value", 5)
        self.flowForce.setObjectName("flowForce")
        self.horizontalLayout_27.addWidget(self.flowForce)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab_7, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.renderBtn = QtWidgets.QPushButton(Dialog)
        self.renderBtn.setObjectName("renderBtn")
        self.verticalLayout.addWidget(self.renderBtn)
        self.verticalLayout.setStretch(10, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.renderFrames = QtWidgets.QPushButton(Dialog)
        self.renderFrames.setObjectName("renderFrames")
        self.horizontalLayout_11.addWidget(self.renderFrames)
        self.renderInterpolation = QtWidgets.QPushButton(Dialog)
        self.renderInterpolation.setObjectName("renderInterpolation")
        self.horizontalLayout_11.addWidget(self.renderInterpolation)
        self.renderVideo = QtWidgets.QPushButton(Dialog)
        self.renderVideo.setObjectName("renderVideo")
        self.horizontalLayout_11.addWidget(self.renderVideo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.renderFrames, self.patreonBtn)
        Dialog.setTabOrder(self.patreonBtn, self.renderVideo)
        Dialog.setTabOrder(self.renderVideo, self.renderBtn)
        Dialog.setTabOrder(self.renderBtn, self.discBtn)
        Dialog.setTabOrder(self.discBtn, self.radioInputVideos)
        Dialog.setTabOrder(self.radioInputVideos, self.radioInputPNG)
        Dialog.setTabOrder(self.radioInputPNG, self.radioResumeRender)
        Dialog.setTabOrder(self.radioResumeRender, self.inputFileBtn)
        Dialog.setTabOrder(self.inputFileBtn, self.inputFolderBtn)
        Dialog.setTabOrder(self.inputFolderBtn, self.inputResumeFolder)
        Dialog.setTabOrder(self.inputResumeFolder, self.renderInterpolation)
        Dialog.setTabOrder(self.renderInterpolation, self.exportType)
        Dialog.setTabOrder(self.exportType, self.outputFolderBtn)
        Dialog.setTabOrder(self.outputFolderBtn, self.animMethod)
        Dialog.setTabOrder(self.animMethod, self.alphaOpt)
        Dialog.setTabOrder(self.alphaOpt, self.intAlgo)
        Dialog.setTabOrder(self.intAlgo, self.fpsInput)
        Dialog.setTabOrder(self.fpsInput, self.interpolationLevel)
        Dialog.setTabOrder(self.interpolationLevel, self.outputFps)
        Dialog.setTabOrder(self.outputFps, self.useSplit)
        Dialog.setTabOrder(self.useSplit, self.splitSizeX)
        Dialog.setTabOrder(self.splitSizeX, self.splitPad)
        Dialog.setTabOrder(self.splitPad, self.useResize)
        Dialog.setTabOrder(self.useResize, self.widthValue)
        Dialog.setTabOrder(self.widthValue, self.dontInterpolateScenes)
        Dialog.setTabOrder(self.dontInterpolateScenes, self.lineEdit_2)
        Dialog.setTabOrder(self.lineEdit_2, self.verifyScenes)
        Dialog.setTabOrder(self.verifyScenes, self.cleanInterpol)
        Dialog.setTabOrder(self.cleanInterpol, self.fpsLimit)
        Dialog.setTabOrder(self.fpsLimit, self.to60)
        Dialog.setTabOrder(self.to60, self.to60C1)
        Dialog.setTabOrder(self.to60C1, self.to60C2)
        Dialog.setTabOrder(self.to60C2, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.interpolMethod)
        Dialog.setTabOrder(self.interpolMethod, self.textEdit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "DAIN-APP _ #DAINAPP"))
        self.credits.setText(_translate("Dialog", "Credits"))
        self.pushButton.setText(_translate("Dialog", "Patrons that made this app possible."))
        self.patreonBtn.setText(_translate("Dialog", "Support the App on Patreon"))
        self.discBtn.setText(_translate("Dialog", "Share results on Discord"))
        self.radioInputVideos.setText(_translate("Dialog", "Input Video(s)"))
        self.radioInputPNG.setText(_translate("Dialog", "Input PNG Sequence"))
        self.radioResumeRender.setText(_translate("Dialog", "Resume Render"))
        self.inputFileBtn.setText(_translate("Dialog", "Input File(s)"))
        self.inputFileLabel.setText(_translate("Dialog", "Input File(s) Path"))
        self.inputFolderBtn.setText(_translate("Dialog", "Input PNG Sequence Folder"))
        self.inputFolderLabel.setText(_translate("Dialog", "Input Folder Path"))
        self.inputResumeFolder.setText(_translate("Dialog", "Render Folder"))
        self.inputResumeLabel.setText(_translate("Dialog", "Resume Render Folder"))
        self.exportType.setItemText(0, _translate("Dialog", "Export as Mp4"))
        self.exportType.setItemText(1, _translate("Dialog", "Export as  WebM"))
        self.exportType.setItemText(2, _translate("Dialog", "Export as  GIF"))
        self.exportType.setItemText(3, _translate("Dialog", "Export as APNG"))
        self.outputFolderBtn.setText(_translate("Dialog", "Output Folder"))
        self.outputFolderLabel.setText(_translate("Dialog", "Selected Output Folder"))
        self.label_27.setText(_translate("Dialog", "Model:"))
        self.flowModel.setItemText(0, _translate("Dialog", "Default Flow Model"))
        self.label_18.setText(_translate("Dialog", "This variable don\'t affect the input if it\'s a PNG sequence."))
        self.label_6.setToolTip(_translate("Dialog", "Select how the app will select and use the original frames from the video."))
        self.label_6.setText(_translate("Dialog", "Frames Handling Mode:"))
        self.interpolMethod.setToolTip(_translate("Dialog", "Select how the app will select and use the original frames from the video."))
        self.interpolMethod.setCurrentText(_translate("Dialog", "Mode 1: Default (all frames treated the same)"))
        self.interpolMethod.setItemText(0, _translate("Dialog", "Mode 1: Default (all frames treated the same)"))
        self.interpolMethod.setItemText(1, _translate("Dialog", "Mode 2: Remove duplicate frames (may alter animation speed)"))
        self.interpolMethod.setItemText(2, _translate("Dialog", "Mode 3: Adaptative Record timestamps then remove duplicate frames (won\'t alter animation speed)"))
        self.interpolMethod.setItemText(3, _translate("Dialog", "Mode 4: Static Record timestamps then remove duplicate frames (won\'t alter animation speed)"))
        self.modeDesc.setText(_translate("Dialog", "Mode description: asdasda \n"
"sdadasdadsa"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Frame Handling Options"))
        self.useHalf.setToolTip(_translate("Dialog", "This option convert float32 to float16 during calculations, this can save some memory and also speed up some calculations."))
        self.useHalf.setText(_translate("Dialog", "Use Half-Precision float"))
        self.doBenchmark.setToolTip(_translate("Dialog", "Pytorch will try to optimize the algorithm with your configurations, it take a little longer to start but it can boost perfomance as well."))
        self.doBenchmark.setText(_translate("Dialog", "Use Pytorch benchmark"))
        self.label_32.setToolTip(_translate("Dialog", "How much frames to process in parallel."))
        self.label_32.setText(_translate("Dialog", "Batch Size:"))
        self.batchSize.setToolTip(_translate("Dialog", "How much frames to process in parallel."))
        self.label_16.setToolTip(_translate("Dialog", "Select what card you want to use to process the video."))
        self.label_16.setText(_translate("Dialog", "Device to use:"))
        self.deviceList.setToolTip(_translate("Dialog", "Select what card you want to use to process the video."))
        self.label_7.setText(_translate("Dialog", "Depth Awareness Mode:"))
        self.animMethod.setItemText(0, _translate("Dialog", "Real life or 3D: Media with clear depth perception."))
        self.animMethod.setItemText(1, _translate("Dialog", "Cartoon or anime: Media with little or no depth."))
        self.label_12.setText(_translate("Dialog", "Interpolation Algorithm:"))
        self.intAlgo.setItemText(0, _translate("Dialog", "Default: 2X/4X/8X; Less Memory; Slower; Cleaner Results"))
        self.intAlgo.setItemText(1, _translate("Dialog", "[Not Working] Experimental: 2X/3X/4X/5X/6X/7X/8X; More Memory; Faster; May generate more artifacts;"))
        self.label_2.setToolTip(_translate("Dialog", "Show what the fps is of the selected file."))
        self.label_2.setText(_translate("Dialog", "Input FPS:"))
        self.fpsInput.setToolTip(_translate("Dialog", "Show what the fps is of the selected file."))
        self.interpolationLevel.setItemText(0, _translate("Dialog", "Interpolate 2X"))
        self.interpolationLevel.setItemText(1, _translate("Dialog", "Interpolate 4X"))
        self.interpolationLevel.setItemText(2, _translate("Dialog", "Interpolate 8X"))
        self.label_5.setText(_translate("Dialog", "Output FPS: "))
        self.label_17.setText(_translate("Dialog", "Note: GIFS above 50FPS will slow down. (This is a gif limitation)"))
        self.label_23.setText(_translate("Dialog", "PNG files compression:"))
        self.pngCompress.setText(_translate("Dialog", "6"))
        self.label_24.setText(_translate("Dialog", "1 gives best speed, 9 gives best compression, 0 gives no compression at all"))
        self.label_26.setText(_translate("Dialog", "Not applied when extracting original_frames from mp4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Interpolation Options"))
        self.label_22.setText(_translate("Dialog", "[MP4 ] CRF value:"))
        self.crfVal.setToolTip(_translate("Dialog", "Change the quality of the output video. 16 usually is fine."))
        self.crfVal.setText(_translate("Dialog", "16"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "Output Options"))
        self.dontInterpolateScenes.setToolTip(_translate("Dialog", "In case of a scene change, interpolation will not occur. Make this value bigger to detect more scenes as a scene change."))
        self.dontInterpolateScenes.setText(_translate("Dialog", "Don\'t interpolate scenes changes"))
        self.label_11.setToolTip(_translate("Dialog", "In case of a scene change, interpolation will not occur. Make this value bigger to detect more scenes as a scene change."))
        self.label_11.setText(_translate("Dialog", "Detection sensitivity:"))
        self.lineEdit_2.setToolTip(_translate("Dialog", "In case of a scene change, interpolation will not occur. Make this value bigger to detect more scenes as a scene change."))
        self.lineEdit_2.setInputMask(_translate("Dialog", "000"))
        self.lineEdit_2.setText(_translate("Dialog", "10"))
        self.verifyScenes.setText(_translate("Dialog", "Verify Scenes Changes"))
        self.cleanInterpol.setToolTip(_translate("Dialog", "If there is files on the interpolation folder, it will remove before starting the process"))
        self.cleanInterpol.setText(_translate("Dialog", "Delete interpolation Folder At Start"))
        self.perfectLoop.setToolTip(_translate("Dialog", "Interpolate the last frame with the first frame of the movie"))
        self.perfectLoop.setText(_translate("Dialog", "Perfect loop animation [The animation repeat in a perfect loop]"))
        self.audioVersion.setText(_translate("Dialog", "Create a output with audio."))
        self.label_10.setToolTip(_translate("Dialog", "Create another output video limiting the fps to X"))
        self.label_10.setText(_translate("Dialog", "If FPS exceeds this value. Create another version with this fps.     [FPS] = "))
        self.fpsLimit.setToolTip(_translate("Dialog", "Create another output video limiting the fps to X"))
        self.fpsLimit.setInputMask(_translate("Dialog", "000"))
        self.fpsLimit.setText(_translate("Dialog", "60"))
        self.to60.setText(_translate("Dialog", "(If FPS exceeds [FPS]) Create a [FPS] version of movie."))
        self.to60C1.setText(_translate("Dialog", "(If FPS exceeds [FPS]) Intepolate down to  [FPS] [Conf 1: Smooth]"))
        self.to60C2.setText(_translate("Dialog", "(If FPS exceeds [FPS]) Intepolate down to  [FPS] [Conf 2: Sharp]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Misc Options"))
        self.Alpha.setText(_translate("Dialog", " [Broken] Alpha Transparency\n"
"[GIF need Limit Color pallet to show alpha]:"))
        self.alphaOpt.setItemText(0, _translate("Dialog", "No Alpha"))
        self.alphaOpt.setItemText(1, _translate("Dialog", "With Alpha"))
        self.limitPalette.setToolTip(_translate("Dialog", "If you are outputing to gif, you want to turn on this option."))
        self.limitPalette.setText(_translate("Dialog", "Limit Color Palette to only use original colors. [Sometimes work better with pixelart]"))
        self.checkBox.setText(_translate("Dialog", "Generate Palette from original frames. [Not working]"))
        self.checkBox_2.setText(_translate("Dialog", "Generate Palette from interpolated frames. [Not working]"))
        self.pixelUpscaleDowscaleBefore.setItemText(0, _translate("Dialog", "Disabled"))
        self.pixelUpscaleDowscaleBefore.setItemText(1, _translate("Dialog", "2X"))
        self.pixelUpscaleDowscaleBefore.setItemText(2, _translate("Dialog", "3X"))
        self.pixelUpscaleDowscaleBefore.setItemText(3, _translate("Dialog", "4X"))
        self.pixelUpscaleDowscaleBefore.setItemText(4, _translate("Dialog", "5X"))
        self.pixelUpscaleDowscaleBefore.setItemText(5, _translate("Dialog", "6X"))
        self.pixelUpscaleDowscaleBefore.setItemText(6, _translate("Dialog", "7X"))
        self.pixelUpscaleDowscaleBefore.setItemText(7, _translate("Dialog", "8X"))
        self.pixelUpscaleDowscaleBefore.setItemText(8, _translate("Dialog", "9X"))
        self.pixelUpscaleDowscaleBefore.setItemText(9, _translate("Dialog", "10X"))
        self.label_19.setText(_translate("Dialog", "Upscale [Nearest neighbor]  by X; Do Interpolation; Downscale[Nearest neighbor]  by X"))
        self.pixelDownscaleUpscaleAfter.setItemText(0, _translate("Dialog", "Disabled"))
        self.pixelDownscaleUpscaleAfter.setItemText(1, _translate("Dialog", "2X"))
        self.pixelDownscaleUpscaleAfter.setItemText(2, _translate("Dialog", "3X"))
        self.pixelDownscaleUpscaleAfter.setItemText(3, _translate("Dialog", "4X"))
        self.pixelDownscaleUpscaleAfter.setItemText(4, _translate("Dialog", "5X"))
        self.pixelDownscaleUpscaleAfter.setItemText(5, _translate("Dialog", "6X"))
        self.pixelDownscaleUpscaleAfter.setItemText(6, _translate("Dialog", "7X"))
        self.pixelDownscaleUpscaleAfter.setItemText(7, _translate("Dialog", "8X"))
        self.pixelDownscaleUpscaleAfter.setItemText(8, _translate("Dialog", "9X"))
        self.pixelDownscaleUpscaleAfter.setItemText(9, _translate("Dialog", "10X"))
        self.label_20.setText(_translate("Dialog", "Do Interpolation; Downscale [Nearest neighbor] by X; Upscale [Nearest neighbor]  by X"))
        self.pixelUpscaleAfter.setItemText(0, _translate("Dialog", "Disabled"))
        self.pixelUpscaleAfter.setItemText(1, _translate("Dialog", "2X"))
        self.pixelUpscaleAfter.setItemText(2, _translate("Dialog", "3X"))
        self.pixelUpscaleAfter.setItemText(3, _translate("Dialog", "4X"))
        self.pixelUpscaleAfter.setItemText(4, _translate("Dialog", "5X"))
        self.pixelUpscaleAfter.setItemText(5, _translate("Dialog", "6X"))
        self.pixelUpscaleAfter.setItemText(6, _translate("Dialog", "7X"))
        self.pixelUpscaleAfter.setItemText(7, _translate("Dialog", "8X"))
        self.pixelUpscaleAfter.setItemText(8, _translate("Dialog", "9X"))
        self.pixelUpscaleAfter.setItemText(9, _translate("Dialog", "10X"))
        self.label_21.setText(_translate("Dialog", "Do Interpolation; Upscale [Nearest neighbor]  by X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PixelArt), _translate("Dialog", "PixelArt"))
        self.label_15.setText(_translate("Dialog", "Keep in mind that other applications also share the VRAM, it\'s almost impossible that Dain-App have all the available VRAM only to itself."))
        self.label_14.setText(_translate("Dialog", "This application runs exclusively on Video memory and requires a LOT of it. For example, rendering at 720p takes between 10 and 11 GB of Vram. \n"
"There are two options to address the issue of a video file being too high resolution to handle with your GPU\'s available Vram capacity (CUDA out of memory error message). \n"
"The faster and easier of the options is to downscale the video to a resolution your GPU can handle. Simply check the downscale box and enter the new height,\n"
"the width will be calculated automatically based on the aspect ratio."))
        self.useResize.setText(_translate("Dialog", "Downscale Video:"))
        self.label_3.setText(_translate("Dialog", "New Height:"))
        self.label_13.setText(_translate("Dialog", "The slower more complicated solution is to use the Frame Splitter, but it will let you render the full resolution of your video.\n"
"This will lower the Vram load by splitting each frame being into pieces (Number of divisions), rendering each piece one at a time, then stitching them back together.\n"
"However, this method causes lines crossing the borders of the pieces to not line up properly, creating  a visible grid pattern where the borders of the pieces are. Padding is used to counteract this.\n"
"Padding is additional space beyond the section size that overlaps with adjacent pieces and is used to ensure the lines between the frames pieces line up properly.\n"
"Keep inscreasing the division size until the Out of Memory error is fixed."))
        self.useSplit.setText(_translate("Dialog", "Split frames into sections:"))
        self.label_8.setText(_translate("Dialog", "Number of divisions X:"))
        self.splitSizeX.setText(_translate("Dialog", "2"))
        self.splitSizeX.setPlaceholderText(_translate("Dialog", "Section Size"))
        self.label_25.setText(_translate("Dialog", "Number of divisions Y:"))
        self.splitSizeY.setText(_translate("Dialog", "2"))
        self.label_9.setText(_translate("Dialog", "Section Padding[px]:"))
        self.splitPad.setText(_translate("Dialog", "150"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Fix OutOfMemory Options"))
        self.label_4.setText(_translate("Dialog", "Color Scheme: "))
        self.brightBtn.setText(_translate("Dialog", "Bright Mode"))
        self.darkBtn.setText(_translate("Dialog", "Dark Mode"))
        self.loadPlace.setText(_translate("Dialog", "Load Preset"))
        self.deletePlace.setText(_translate("Dialog", "Delete Preset"))
        self.placeholderName.setPlaceholderText(_translate("Dialog", "Placeholder name"))
        self.savePlace.setText(_translate("Dialog", "Save New Preset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Application Style"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">How do i start?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dain-App is slow to render long videos or videos with great quality,if you are new to it start with something small like a gif or a 3 second video before starting to use the application.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The simplest test you can do is just select a &quot;input file&quot;e and &quot;output Folder&quot; and press &quot;Perform all steps&quot;, this should create your first interpolation in the selected folder.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">I Get Out Of memory Error even with the split option turned on?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You need to add even more splits.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "FAQ"))
        self.fastMode.setToolTip(_translate("Dialog", "<html><head/><body><p>Will make interpolation a lot faster and use less Vram. But it also produce worse results. Good if you don\'t care much for the final quality or is testing configurations.</p><p>Try it with bigger batch sizes to gain even more speed.</p></body></html>"))
        self.fastMode.setText(_translate("Dialog", "Fast Mode"))
        self.dontCleanCache.setText(_translate("Dialog", "Don\'t clean CUDA cache between frames"))
        self.ffmpegPrint.setText(_translate("Dialog", "Print on console FFMPEG messages."))
        self.onlyInterpolateMissing.setText(_translate("Dialog", "[For internal debugging] Only interpolate deleted frames."))
        self.debugKeepDuplicates.setText(_translate("Dialog", "[For internal debugging] Don\'t use mpdecimate"))
        self.label_31.setText(_translate("Dialog", "Motion Blur {WIP}:"))
        self.label_30.setToolTip(_translate("Dialog", "<html><head/><body><p>[Not work with fast mode enabled]</p><p>[Still WIP]</p><p>0 = Disabled</p><p>2 = Subtle blur</p><p>5 = Small blur</p><p>10 = A lot of blur</p><p>Above 10 = Absurd blur</p></body></html>"))
        self.label_30.setText(_translate("Dialog", "Motion Blur Force [0 = Disable]:"))
        self.smoothFlow.setToolTip(_translate("Dialog", "<html><head/><body><p>[Not work with fast mode enabled]</p><p>[Still WIP]</p><p>0 = Disabled</p><p>2 = Subtle blur</p><p>5 = Small blur</p><p>10 = A lot of blur</p><p>Above 10 = Absurd blur</p></body></html>"))
        self.label_29.setToolTip(_translate("Dialog", "<html><head/><body><p>0   = All motion create motion blur</p><p>5   = Almost all motion create blur</p><p>15 = Faster motions create blur</p><p>Above 20 = Only real fast motions create blur</p></body></html>"))
        self.label_29.setText(_translate("Dialog", "Motion Blur Threshold"))
        self.flowForce.setToolTip(_translate("Dialog", "<html><head/><body><p>0   = All motion create motion blur</p><p>5   = Almost all motion create blur</p><p>15 = Faster motions create blur</p><p>Above 20 = Only real fast motions create blur</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Beta Options"))
        self.renderBtn.setText(_translate("Dialog", "Perform all steps: Render"))
        self.renderFrames.setText(_translate("Dialog", "Step 1: Split source video into frames"))
        self.renderInterpolation.setText(_translate("Dialog", "Step 2: Feed source frames to DAIN"))
        self.renderVideo.setText(_translate("Dialog", "Step 3: Convert DAIN frames to video"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

